"""initial

Revision ID: b8483a7a6c37
Revises: 
Create Date: 2025-09-15 04:55:24.297396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b8483a7a6c37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_aliases', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_understanding', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('products', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_is_placeholder'), 'companies', ['is_placeholder'], unique=False)
    op.create_table('llm_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'call_type', 'date', name='llm_costs_model_call_type_date')
    )
    op.create_table('company_crawls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crawl_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_crawls_company_id'), 'company_crawls', ['company_id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='competitors_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['companies.id'], name='competitors_competitor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'competitor_id')
    )
    op.create_index(op.f('ix_competitors_company_id'), 'competitors', ['company_id'], unique=False)
    op.create_index(op.f('ix_competitors_competitor_id'), 'competitors', ['competitor_id'], unique=False)
    op.create_table('monitored_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('target_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('task_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='monitored_prompts_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_prompts_company_id'), 'monitored_prompts', ['company_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('competitor_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompts_to_analyze', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('why_competitor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('why_not_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('what_to_do', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_company_id'), 'recommendations', ['company_id'], unique=False)
    op.create_index(op.f('ix_recommendations_competitor_domain'), 'recommendations', ['competitor_domain'], unique=False)
    op.create_table('monitored_prompt_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitored_prompt_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('top_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('company_domain_rank', sa.Integer(), nullable=True),
    sa.Column('mentioned_pages', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['monitored_prompt_id'], ['monitored_prompts.id'], name='monitored_prompt_runs_monitored_prompt_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_prompt_runs_monitored_prompt_id'), 'monitored_prompt_runs', ['monitored_prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitored_prompt_runs_monitored_prompt_id'), table_name='monitored_prompt_runs')
    op.drop_table('monitored_prompt_runs')
    op.drop_index(op.f('ix_recommendations_competitor_domain'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_company_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_monitored_prompts_company_id'), table_name='monitored_prompts')
    op.drop_table('monitored_prompts')
    op.drop_index(op.f('ix_competitors_competitor_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_company_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_company_crawls_company_id'), table_name='company_crawls')
    op.drop_table('company_crawls')
    op.drop_table('llm_costs')
    op.drop_index(op.f('ix_companies_is_placeholder'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
